name: ktlint
on:
  pull_request:
    branches:
      - develop
  push:
    paths:
      - '**.kt'
jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          android: true
          fail_on_error: true
          level: warning
